config/routes.rb
Rails.application.routes.draw do
  resources :burgers, only: [:show, :index]
  root 'burgers#index'

end

app/models/burger.rb
class Burger < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/burgers_controller.rb
class BurgersController < ApplicationController
  before_action :set_burger, only: [:show, :edit, :update, :destroy]

  # GET /burgers
  # GET /burgers.json
  def index
    @burgers = Burger.all
  end

  # GET /burgers/1
  # GET /burgers/1.json
  def show
  end

  # GET /burgers/new
  def new
    @burger = Burger.new
  end

  # GET /burgers/1/edit
  def edit
  end

  # POST /burgers
  # POST /burgers.json
  def create
    @burger = Burger.new(burger_params)

    respond_to do |format|
      if @burger.save
        format.html { redirect_to @burger, notice: 'Burger was successfully created.' }
        format.json { render :show, status: :created, location: @burger }
      else
        format.html { render :new }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /burgers/1
  # PATCH/PUT /burgers/1.json
  def update
    respond_to do |format|
      if @burger.update(burger_params)
        format.html { redirect_to @burger, notice: 'Burger was successfully updated.' }
        format.json { render :show, status: :ok, location: @burger }
      else
        format.html { render :edit }
        format.json { render json: @burger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /burgers/1
  # DELETE /burgers/1.json
  def destroy
    @burger.destroy
    respond_to do |format|
      format.html { redirect_to burgers_url, notice: 'Burger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_burger
      @burger = Burger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def burger_params
      params.require(:burger).permit(:name, :price, :description, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/burgers_helper.rb
module BurgersHelper
end

app/views/burgers/_form.html.erb
<%= form_for(@burger) do |f| %>
  <% if @burger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@burger.errors.count, "error") %> prohibited this burger from being saved:</h2>

      <ul>
      <% @burger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/burgers/edit.html.erb
<h1>Editing Burger</h1>

<%= render 'form' %>

<%= link_to 'Show', @burger %> |
<%= link_to 'Back', burgers_path %>

app/views/burgers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Burgers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @burgers.each do |burger| %>
      <tr>
        <td><%= burger.name %></td>
        <td><%= burger.price %></td>
        <td><%= burger.description %></td>
        <td><%= burger.image_url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/burgers/new.html.erb
<h1>New Burger</h1>

<%= render 'form' %>

<%= link_to 'Back', burgers_path %>

app/views/burgers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @burger.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @burger.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @burger.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @burger.image_url %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
      <div class="row">
        <div class="large-12 columns">
     
         
          <div class="row">
            <div class="large-12 columns">
     
              <nav class="top-bar" data-topbar>
                <ul class="title-area">
                   
                  <li class="name">
                    <h1>
                      <a href="#">
                        BurgerCore
                      </a>
                    </h1>
                  </li>
                  
                </ul>

            <div class="large-8 columns">
              <div class="row">
     
                <div class="large-4 small-6 columns">
                  <img src="http://i.imgur.com/StVxSIS.png">
     
                  <div class="panel">
                    <h5>Item Name</h5>
                    <h6 class="subheader">$000.00</h6>
                  </div>
                </div>
     
                <div class="large-4 small-6 columns">
                  <img src="http://placehold.it/500x500&text=Thumbnail">
     
                  <div class="panel">
                    <h5>Item Name</h5>
                    <h6 class="subheader">$000.00</h6>
                  </div>
                </div>
     
                <div class="large-4 small-6 columns">
                  <img src="http://placehold.it/500x500&text=Thumbnail">
     
                  <div class="panel">
                    <h5>Item Name</h5>
                    <h6 class="subheader">$000.00</h6>
                  </div>
                </div>
     
                <div class="large-4 small-6 columns">
                  <img src="http://placehold.it/500x500&text=Thumbnail">
     
                  <div class="panel">
                    <h5>Item Name</h5>
                    <h6 class="subheader">$000.00</h6>
                  </div>
                </div>
     
                <div class="large-4 small-6 columns">
                  <img src="http://placehold.it/500x500&text=Thumbnail">
     
                  <div class="panel">
                    <h5>Item Name</h5>
                    <h6 class="subheader">$000.00</h6>
                  </div>
                </div>
     
                <div class="large-4 small-6 columns">
                  <img src="http://placehold.it/500x500&text=Thumbnail">
     
                  <div class="panel">
                    <h5>Item Name</h5>
                    <h6 class="subheader">$000.00</h6>
                  </div>
                </div>
              </div>
     
              <div class="row">
                <div class="large-12 columns">
                  <div class="panel">
                    <div class="row">
     
                      <div class="large-2 small-6 columns">
                        <img src="http://placehold.it/300x300&text=Site Owner">
                      </div>
     
                      <div class="large-10 small-6 columns">
                        <strong>This Site Is Managed By<hr/></strong>
     
                        Risus ligula, aliquam nec fermentum vitae, sollicitudin eget urna. Donec dignissim nibh fermentum odio ornare sagittis
                      </div>
     
                    </div>
                  </div>
                </div>
     
         
     
              </div>
            </div>
          </div>
     
     
         
     
          <footer class="row">
            <div class="large-12 columns"><hr/>
              <div class="row">
     
                <div class="large-6 columns">
                  <p>© Copyright no one at all. Go to town.</p>
                </div>
     
                <div class="large-6 columns">
                  <ul class="inline-list right">
                    <li><a href="#">Link 1</a></li>
                    <li><a href="#">Link 2</a></li>
                    <li><a href="#">Link 3</a></li>
                    <li><a href="#">Link 4</a></li>
                  </ul>
                </div>
     
              </div>
            </div>
          </footer>
     
         
     
        </div>
      </div>
</html>